### Pivot Table Using Pandas

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Online Assesment - Business Data Support - Nur Syahril - Pelayanan Harian.csv')
df

,Tanggal Jadwal Kunjungan,Poli,Jumlah Kunjungan,Hari,Unnamed: 4,Unnamed: 5
0,2023-05-02,ANAK (UMUR DIBAWAH 5 TAHUN),11,Tuesday,NaN,\n
1,2023-05-02,ILI (BATUK PILEK DEMAM),19,Tuesday,NaN,NaN
2,2023-05-02,IMUNISASI,5,Tuesday,NaN,NaN
3,2023-05-02,KEUR (SURAT SEHAT),2,Tuesday,NaN,NaN
4,2023-05-02,KONSULTASI,1,Tuesday,NaN,NaN
...,...,...,...,...,...,...
115,2023-05-13,POLI GIGI DAN MULUT,9,Saturday,NaN,NaN
116,2023-05-13,POLI KB,4,Saturday,NaN,NaN
117,2023-05-13,POLI TB & PARU,2,Saturday,NaN,NaN
118,2023-05-13,PTM (KONTROL GULA/DARAH TINGGI),1,Saturday,NaN,NaN
119,2023-05-13,UMUM (Bukan untuk bapil),31,Saturday,NaN,NaN

In [3]:
columns_to_drop = ['Unnamed: 4', 'Unnamed: 5']
df = df.drop(columns_to_drop, axis=1)

In [4]:
df

,Tanggal Jadwal Kunjungan,Poli,Jumlah Kunjungan,Hari
0,2023-05-02,ANAK (UMUR DIBAWAH 5 TAHUN),11,Tuesday
1,2023-05-02,ILI (BATUK PILEK DEMAM),19,Tuesday
2,2023-05-02,IMUNISASI,5,Tuesday
3,2023-05-02,KEUR (SURAT SEHAT),2,Tuesday
4,2023-05-02,KONSULTASI,1,Tuesday
...,...,...,...,...
115,2023-05-13,POLI GIGI DAN MULUT,9,Saturday
116,2023-05-13,POLI KB,4,Saturday
117,2023-05-13,POLI TB & PARU,2,Saturday
118,2023-05-13,PTM (KONTROL GULA/DARAH TINGGI),1,Saturday
119,2023-05-13,UMUM (Bukan untuk bapil),31,Saturday

In [5]:
df_rabu = df[df['Hari'] == 'Wednesday']
df_rabu

,Tanggal Jadwal Kunjungan,Poli,Jumlah Kunjungan,Hari
13,2023-05-03,ANAK (UMUR DIBAWAH 5 TAHUN),5,Wednesday
14,2023-05-03,ILI (BATUK PILEK DEMAM),21,Wednesday
15,2023-05-03,KIA (PERIKSA HAMIL),18,Wednesday
16,2023-05-03,KONSULTASI,1,Wednesday
17,2023-05-03,LABORATORIUM,10,Wednesday
18,2023-05-03,LANSIA (60thn keatas),13,Wednesday
19,2023-05-03,POLI GIGI DAN MULUT,4,Wednesday
20,2023-05-03,POLI TB & PARU,2,Wednesday
21,2023-05-03,UMUM (Bukan untuk bapil),29,Wednesday
80,2023-05-10,ANAK (UMUR DIBAWAH 5 TAHUN),9,Wednesday
81,2023-05-10,ILI (BATUK PILEK DEMAM),18,Wednesday
82,2023-05-10,KEUR (SURAT SEHAT),4,Wednesday
83,2023-05-10,KIA (PERIKSA HAMIL),14,Wednesday
84,2023-05-10,LABORATORIUM,4,Wednesday
85,2023-05-10,LANSIA (60thn keatas),8,Wednesday
86,2023-05-10,POLI GIGI DAN MULUT,4,Wednesday
87,2023-05-10,POLI TB & PARU,1,Wednesday
88,2023-05-10,UMUM (Bukan untuk bapil),25,Wednesday

In [6]:
pivot_table = pd.pivot_table(data=df_rabu,
                             values='Jumlah Kunjungan',
                             index='Tanggal Jadwal Kunjungan',
                             columns='Poli',
                             aggfunc='sum')

In [7]:
pivot_table

Poli,ANAK (UMUR DIBAWAH 5 TAHUN),ILI (BATUK PILEK DEMAM),KEUR (SURAT SEHAT),KIA (PERIKSA HAMIL),KONSULTASI,LABORATORIUM,LANSIA (60thn keatas),POLI GIGI DAN MULUT,POLI TB & PARU,UMUM (Bukan untuk bapil)
Tanggal Jadwal Kunjungan,,,,,,,,,,
2023-05-03,5.0,21.0,NaN,18.0,1.0,10.0,13.0,4.0,2.0,29.0
2023-05-10,9.0,18.0,4.0,14.0,NaN,4.0,8.0,4.0,1.0,25.0

In [14]:
# save into csv
pivot_table.to_csv('pivot_table.csv', index=True)

### [Optional] Pivot Table using Pivot UI Library

In [8]:
# download library
from pivottablejs import pivot_ui

In [15]:
# make into html
pivot_ui(df)

The code above will generate a html file called 'pivottablejs.html' and you can edit the pivot table there. This is the example pivot table ouput for number of visits on each 'Tanggal Kunjungan' and 'Poli', but only on Wednesdays.

![Pivot Table Ouput](pivot_table_output_rabu.png "Pivot Table")